#!/bin/bash

# complements of @slaphost

# /usr/bin/sudo -u DesignAndDevelopment /usr/bin/osascript "/Users/DesignAndDevelopment/Effects/currentlyplaying.scpt"

# echo "that's what's current"

/usr/bin/osascript /Users/DesignAndDevelopment/Effects/currentlyplaying.scpt $1

echo $1
