#! /bin/sh

#site="tell application \"Safari\" to open location \"$1\""
#osascript -e "$site"

/usr/bin/osascript /Users/DesignAndDevelopment/Projects/Sounds/applescripts/project.scpt "$@"

echo "$@"
